[2022-11-10 00:37:41,267] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'add_job' ((2013, 'Lost connection to MySQL server during query')). Retrying with a new DB connection...
[2022-11-10 00:37:53,818] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'add_job' ((2003, "Can't connect to MySQL server on 'capstone.czjd9ym4s3b2.ap-southeast-1.rds.amazonaws.com' ([Errno -3] Try again)")). Retrying with a new DB connection...
[2022-11-10 00:38:06,734] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing 'add_job' ((2003, "Can't connect to MySQL server on 'capstone.czjd9ym4s3b2.ap-southeast-1.rds.amazonaws.com' ([Errno -3] Try again)")). Retrying with a new DB connection...
[2022-11-10 13:59:51,300] WARNING [django.request.log_response:241] Not Found: /favicon.ico
