[2022-10-22 01:21:24,559] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:31:22,781] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:33:40,694] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:35:47,920] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:36:26,270] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:36:59,477] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:39:18,878] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:41:20,476] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:41:35,655] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:41:47,364] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:43:06,239] ERROR [shared.exception_handler.__handle_attribute_error:122] 'Doctor' object has no attribute 'name'
[2022-10-22 01:43:06,241] ERROR [django.request.log_response:241] Internal Server Error: /appointments/
[2022-10-22 01:44:00,660] ERROR [shared.exception_handler.__handle_attribute_error:122] 'Appointment' object has no attribute 'type'
[2022-10-22 01:44:00,662] ERROR [django.request.log_response:241] Internal Server Error: /appointments/
[2022-10-22 01:46:09,149] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job '1666403168.205676' no longer exists! Skipping logging of job execution...
[2022-10-22 01:46:10,008] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job '1666403168.205676' no longer exists! Skipping logging of job execution...
[2022-10-22 01:51:25,079] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=119 | run_date=2022-10-22 01:49:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 01:51:25,397] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job '1666403305.01782' no longer exists! Skipping logging of job execution...
[2022-10-22 01:51:25,705] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job '1666403305.01782' no longer exists! Skipping logging of job execution...
[2022-10-22 01:51:26,024] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=119 | run_date=2022-10-22 01:49:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 01:56:32,929] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 01:56:44,611] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 02:22:06,001] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 02:22:19,195] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing '_get_jobs' ((2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")). Retrying with a new DB connection...
[2022-10-22 02:22:21,908] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job '1666405340.936834' no longer exists! Skipping logging of job execution...
[2022-10-22 02:22:21,989] ERROR [apscheduler.executors.default.run_job:131] Job "send_notification (trigger: date[2022-10-22 02:22:20 UTC], next run at: 2022-10-22 02:22:20 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/src/app/appointment/serializers.py", line 83, in send_notification
    devices.send_message(
  File "/usr/local/lib/python3.10/site-packages/fcm_django/models.py", line 170, in send_message
    messaging.send_all(
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 136, in send_all
    return _get_messaging_service(app).send_all(messages, dry_run)
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 379, in send_all
    body = json.dumps(self._message_data(message, dry_run))
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 429, in _message_data
    data = {'message': _MessagingService.encode_message(message)}
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 342, in encode_message
    return cls.JSON_ENCODER.default(message)
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/_messaging_encoder.py", line 671, in default
    'notification': MessageEncoder.encode_notification(o.notification),
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/_messaging_encoder.py", line 641, in encode_notification
    raise ValueError('Message.notification must be an instance of Notification class.')
ValueError: Message.notification must be an instance of Notification class.
[2022-10-22 02:22:22,321] WARNING [django_apscheduler.jobstores.handle_error_event:160] Job '1666405340.936834' no longer exists! Skipping logging of job execution...
[2022-10-22 02:23:06,234] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=120 | run_date=2022-10-22 02:23:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:23:06,681] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=120 | run_date=2022-10-22 02:23:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:27:10,709] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 02:27:21,451] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 02:28:03,223] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job '1666405682.218655' no longer exists! Skipping logging of job execution...
[2022-10-22 02:28:03,246] ERROR [apscheduler.executors.default.run_job:131] Job "send_notification (trigger: date[2022-10-22 02:28:02 UTC], next run at: 2022-10-22 02:28:02 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/src/app/appointment/serializers.py", line 84, in send_notification
    devices.send_message(
  File "/usr/local/lib/python3.10/site-packages/fcm_django/models.py", line 170, in send_message
    messaging.send_all(
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 136, in send_all
    return _get_messaging_service(app).send_all(messages, dry_run)
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 379, in send_all
    body = json.dumps(self._message_data(message, dry_run))
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 429, in _message_data
    data = {'message': _MessagingService.encode_message(message)}
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 342, in encode_message
    return cls.JSON_ENCODER.default(message)
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/_messaging_encoder.py", line 671, in default
    'notification': MessageEncoder.encode_notification(o.notification),
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/_messaging_encoder.py", line 641, in encode_notification
    raise ValueError('Message.notification must be an instance of Notification class.')
ValueError: Message.notification must be an instance of Notification class.
[2022-10-22 02:28:03,565] WARNING [django_apscheduler.jobstores.handle_error_event:160] Job '1666405682.218655' no longer exists! Skipping logging of job execution...
[2022-10-22 02:28:06,271] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=121 | run_date=2022-10-22 02:28:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:28:06,736] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=121 | run_date=2022-10-22 02:28:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:30:22,325] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 02:30:44,428] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 02:30:54,653] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job '1666405853.635821' no longer exists! Skipping logging of job execution...
[2022-10-22 02:30:55,674] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job '1666405853.635821' no longer exists! Skipping logging of job execution...
[2022-10-22 02:32:06,445] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=122 | run_date=2022-10-22 02:32:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:32:06,776] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=122 | run_date=2022-10-22 02:32:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:41:23,856] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 02:41:39,993] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job '1666406499.022984' no longer exists! Skipping logging of job execution...
[2022-10-22 02:41:40,118] ERROR [apscheduler.executors.default.run_job:131] Job "send_notification (trigger: date[2022-10-22 02:41:39 UTC], next run at: 2022-10-22 02:41:39 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/src/app/appointment/serializers.py", line 85, in send_notification
    devices.send_message(
  File "/usr/local/lib/python3.10/site-packages/fcm_django/models.py", line 170, in send_message
    messaging.send_all(
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 136, in send_all
    return _get_messaging_service(app).send_all(messages, dry_run)
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 379, in send_all
    body = json.dumps(self._message_data(message, dry_run))
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 429, in _message_data
    data = {'message': _MessagingService.encode_message(message)}
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 342, in encode_message
    return cls.JSON_ENCODER.default(message)
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/_messaging_encoder.py", line 670, in default
    'data': _Validators.check_string_dict('Message.data', o.data),
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/_messaging_encoder.py", line 122, in check_string_dict
    raise ValueError('{0} must be a dictionary.'.format(label))
ValueError: Message.data must be a dictionary.
[2022-10-22 02:41:40,462] WARNING [django_apscheduler.jobstores.handle_error_event:160] Job '1666406499.022984' no longer exists! Skipping logging of job execution...
[2022-10-22 02:42:06,422] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=123 | run_date=2022-10-22 02:42:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:42:06,743] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=123 | run_date=2022-10-22 02:42:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:43:38,447] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 02:43:49,318] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job '1666406628.294236' no longer exists! Skipping logging of job execution...
[2022-10-22 02:43:49,439] ERROR [apscheduler.executors.default.run_job:131] Job "send_notification (trigger: date[2022-10-22 02:43:48 UTC], next run at: 2022-10-22 02:43:48 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/src/app/appointment/serializers.py", line 85, in send_notification
    devices.send_message(
  File "/usr/local/lib/python3.10/site-packages/fcm_django/models.py", line 170, in send_message
    messaging.send_all(
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 136, in send_all
    return _get_messaging_service(app).send_all(messages, dry_run)
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 379, in send_all
    body = json.dumps(self._message_data(message, dry_run))
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 429, in _message_data
    data = {'message': _MessagingService.encode_message(message)}
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/messaging.py", line 342, in encode_message
    return cls.JSON_ENCODER.default(message)
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/_messaging_encoder.py", line 670, in default
    'data': _Validators.check_string_dict('Message.data', o.data),
  File "/usr/local/lib/python3.10/site-packages/firebase_admin/_messaging_encoder.py", line 128, in check_string_dict
    raise ValueError('{0} must not contain non-string values.'.format(label))
ValueError: Message.data must not contain non-string values.
[2022-10-22 02:43:49,788] WARNING [django_apscheduler.jobstores.handle_error_event:160] Job '1666406628.294236' no longer exists! Skipping logging of job execution...
[2022-10-22 02:45:06,344] WARNING [appointment.serializers.perform_check_appointment:58] Appointment matching query does not exist.
[2022-10-22 02:45:06,560] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=124 | run_date=2022-10-22 02:45:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:45:06,871] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=124 | run_date=2022-10-22 02:45:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:45:10,059] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 02:45:20,560] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job '1666406719.519544' no longer exists! Skipping logging of job execution...
[2022-10-22 02:45:21,062] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job '1666406719.519544' no longer exists! Skipping logging of job execution...
[2022-10-22 02:46:06,431] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=125 | run_date=2022-10-22 02:46:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 02:46:06,793] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=125 | run_date=2022-10-22 02:46:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 03:31:19,092] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 03:31:29,669] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 03:31:40,570] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job '1666409499.418127' no longer exists! Skipping logging of job execution...
[2022-10-22 03:31:41,649] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job '1666409499.418127' no longer exists! Skipping logging of job execution...
[2022-10-22 03:32:06,564] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=126 | run_date=2022-10-22 03:32:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 03:32:06,877] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=126 | run_date=2022-10-22 03:32:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 03:41:15,064] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 03:42:24,641] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 03:45:16,724] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 03:45:24,879] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 03:45:32,902] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 04:05:54,571] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 04:07:06,095] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=129 | run_date=2022-10-22 04:07:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:07:06,441] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=129 | run_date=2022-10-22 04:07:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:09:05,780] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=130 | run_date=2022-10-22 04:09:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:09:06,125] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=130 | run_date=2022-10-22 04:09:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:10:05,800] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=131 | run_date=2022-10-22 04:10:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:10:06,142] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=131 | run_date=2022-10-22 04:10:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:12:00,801] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 04:12:35,803] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=132 | run_date=2022-10-22 04:12:35+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:12:36,142] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=132 | run_date=2022-10-22 04:12:35+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:13:05,773] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=133 | run_date=2022-10-22 04:13:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:13:06,115] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=133 | run_date=2022-10-22 04:13:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:51:06,069] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=134 | run_date=2022-10-22 04:51:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:51:06,382] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=134 | run_date=2022-10-22 04:51:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:57:06,035] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=135 | run_date=2022-10-22 04:57:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:57:06,347] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=135 | run_date=2022-10-22 04:57:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:59:06,030] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=136 | run_date=2022-10-22 04:59:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 04:59:06,361] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=136 | run_date=2022-10-22 04:59:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:02:05,732] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=137 | run_date=2022-10-22 05:02:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:02:06,042] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=137 | run_date=2022-10-22 05:02:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:04:05,754] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=138 | run_date=2022-10-22 05:04:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:04:06,066] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=138 | run_date=2022-10-22 05:04:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:14:56,531] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 05:15:03,729] WARNING [django.request.log_response:241] Bad Request: /appointments/
[2022-10-22 05:15:05,671] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=139 | run_date=2022-10-22 05:15:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:15:05,947] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=139 | run_date=2022-10-22 05:15:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:16:05,722] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=140 | run_date=2022-10-22 05:16:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:16:06,031] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=140 | run_date=2022-10-22 05:16:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:17:05,730] WARNING [django_apscheduler.jobstores.handle_execution_event:107] Job 'appointmentId=141 | run_date=2022-10-22 05:17:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:17:06,047] WARNING [django_apscheduler.jobstores.handle_submission_event:78] Job 'appointmentId=141 | run_date=2022-10-22 05:17:05+00:00' no longer exists! Skipping logging of job execution...
[2022-10-22 05:52:03,497] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-10-22 09:00:05,865] WARNING [django_apscheduler.util.func_wrapper:100] DB error executing '_get_jobs' ((2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")). Retrying with a new DB connection...
