[2022-11-26 14:28:31,130] WARNING [django.request.log_response:241] Unauthorized: /user/health-records/
[2022-11-26 14:31:50,614] ERROR [django.request.log_response:241] Internal Server Error: /user/health-records/
[2022-11-26 14:33:10,197] ERROR [shared.exception_handler.__handle_http404:112] Patient matching query does not exist.
[2022-11-26 14:33:10,198] WARNING [django.request.log_response:241] Not Found: /user/health-records/
[2022-11-26 14:33:15,506] ERROR [shared.exception_handler.__handle_http404:112] Patient matching query does not exist.
[2022-11-26 14:33:15,508] WARNING [django.request.log_response:241] Not Found: /user/health-records/
[2022-11-26 14:33:24,072] ERROR [shared.exception_handler.__handle_http404:112] Patient matching query does not exist.
[2022-11-26 14:33:24,074] WARNING [django.request.log_response:241] Not Found: /user/health-records/
